info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    bookpurchase:
      path: /bp/**
      serviceId: bookpurchase-service
    bookinventory: 
      path: /bi/**
      serviceId: bookinventory-service
    booklending:
      path: /bl/**
      serviceId: booklending-service
    
             

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetch-registry: true
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG